apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icap-adaptation
  name: rebuild-rest-api
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: rebuild-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rebuild-rest-api
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"  
      containers:
      - name: rebuild-rest-api
        image: llmsjraj/gw:rebuild
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi       
---
apiVersion: v1
kind: Service
metadata:
  namespace: icap-adaptation
  name: rebuild-rest-api
  labels:
    service: rebuild-rest-api
spec:
  selector:
    app: rebuild-rest-api
  ports:
    - name: api-port
      port:  8090
      targetPort: 80
  type: LoadBalancer
