apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icap-adaptation
  name: proxy-rest-api
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: proxy-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proxy-rest-api
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"  
      volumes:
        - name: source-vol
          persistentVolumeClaim:
            claimName: glasswallsource-pvc
        - name: target-vol
          persistentVolumeClaim:
            claimName: glasswalltarget-pvc
        - name: transaction-query-service-vol
          persistentVolumeClaim:
            claimName: pvc-transaction-query-service                  
      containers:
      - name: proxy-rest-api
        image: k8serviceaccount/cs-k8s-api:mohit-ticket-618
        imagePullPolicy: Always  
        securityContext:
          capabilities:
            drop:
              - all
          allowPrivilegeEscalation: false
          runAsNonRoot: true      
          runAsUser: 1000
          runAsGroup: 2000
        ports:
        - containerPort: 8080  
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
          - mountPath: "/var/source"
            name: source-vol
          - mountPath: "/var/target"
            name: target-vol
          - mountPath: "/mnt/stores/transactions"
            name: transaction-query-service-vol
        env:
        - name: ProcessingTimeoutDuration
          value: "00:10:00"
        - name: OriginalStorePath
          value: "/app/source"
        - name: RebuiltStorePath
          value: "/app/target"
        - name: ExchangeName
          value: "adaptation-exchange"
        - name: RequestQueueName
          value: "adaptation-request-queue"
        - name: OutcomeQueueName
          value: "amq.rabbitmq.reply-to"
        - name: RequestMessageName
          value: "adaptation-request"
        - name: MBHostName
          value: "rabbitmq-service"
        - name: MBPort
          value: "5672"    
        - name: SDKEngineVersion
          value: "1.5"            
---
apiVersion: v1
kind: Service
metadata:
  namespace: icap-adaptation
  name: proxy-rest-api
  labels:
    service: proxy-rest-api
spec:
  selector:
    app: proxy-rest-api
  ports:
    - name: api-port
      port:  8080
      targetPort: 8080
  type: LoadBalancer
